# Site Settings
title: "Elizabeth Lawrence"
name: "Elizabeth Lawrence"
description: "Professional portfolio and CV"
url: "https://elilawrence.github.io"
repository: "elilawrence/elilawrence.github.io"

# Theme
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
minimal_mistakes_skin: "air" # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"
head_scripts:
  - /assets/css/style.css
# Author info (appears in sidebar/footer)
author:
  name: "Elizabeth Lawrence"
  avatar: "/assets/images/portrait.jpg"
  bio: "Ecologist, Training Officer, Data Standards"
  location: "Montreal, Canada"
  email: "e.lawrence@obis.org"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/elilawrence"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://linkedin.com/in/elilawrence"

# Build settings
markdown: kramdown
permalink: /:title/
paginate: 5
timezone: America/Montreal

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-include-cache

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
  - scope:
      path: ""
    values:
      layout: single
      author_profile: true

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor